name: KingMCDonate
version: '$version'
main: net.kingmc.plugin.kingmcdonate.KingMCDonate
api-version: '1.16'
folia-supported: true
authors: [KhanhHuynh]

depend: [packetevents]
softdepend: [PlayerPoints, Vault, PlaceholderAPI, floodgate]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.4.0
  - com.github.cryptomorin:XSeries:13.7.0
  - com.google.code.gson:gson:2.14.0
  - com.zaxxer:HikariCP:7.0.2
  - org.xerial:sqlite-jdbc:3.53.2.0
  - com.mysql:mysql-connector-j:9.7.0

commands:
  napthe:
    description: Mở GUI nạp thẻ hoặc nạp nhanh
    usage: /napthe [loại] [mệnh giá] [seri] [pin]
    permission: kingmcdonate.napthe
  bank:
    description: Nạp tiền qua QR ngân hàng
    usage: /bank <số tiền>
    permission: kingmcdonate.bank
  topnap:
    description: Xem top nạp
    usage: /topnap
    permission: kingmcdonate.topnap
  napbossbar:
    description: Bật/tắt thanh tiến độ mốc nạp
    usage: /napbossbar
    permission: kingmcdonate.bossbar
  lichsunap:
    description: Xem lịch sử nạp
    usage: /lichsunap [player]
    permission: kingmcdonate.lichsu
  kingmcdonate:
    description: Lệnh quản trị KingMCDonate
    usage: /kingmcdonate <reload|lichsu|fakecard|fakebank|give|reconcile>
    permission: kingmcdonate.admin

permissions:
  kingmcdonate.napthe:
    description: Cho phép nạp thẻ
    default: true
  kingmcdonate.bank:
    description: Cho phép nạp qua ngân hàng
    default: true
  kingmcdonate.topnap:
    description: Cho phép xem top nạp
    default: true
  kingmcdonate.lichsu:
    description: Cho phép xem lịch sử nạp
    default: true
  kingmcdonate.admin:
    description: Quyền quản trị KingMCDonate
    default: op
  kingmcdonate.bossbar:
    description: Cho phép bật/tắt bossbar mốc nạp
    default: true
